name = "clases-bot"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "clases-db"
database_id = "5ebf2f88-4c0c-4766-85ef-2c5b65ed87e2"
preview_database_id = "5ebf2f88-4c0c-4766-85ef-2c5b65ed87e2"

